// authorize-override — verify a second person, and do not become them.
//
// A cashier cannot void a line. A supervisor can. This function answers one
// question — "is this PIN right, and does this person hold this permission in
// this store?" — and returns that answer and nothing else. The grant itself is
// minted on the terminal, where the session that receives it lives.
//
// It exists so that a supervisor who has never signed in on a particular till
// can still authorise there when the network is up. Offline, the terminal
// checks the PIN against `cached_users`, which only works for somebody it has
// seen before.
//
// ## What this function must never grow
//
// `authenticate-pin` sits in the next directory and ends with about forty
// lines of `generateLink` + `verifyOtp` that mint a real Supabase session.
// Copying that file and deleting the wrong half would hand the till a
// supervisor's session every time a cashier voided a line — and it would look
// like it worked, because the grant would be minted too. The property being
// protected has a name, from the commit that built the offline path:
// *verify a second person without becoming them*. The whole point of an
// override is that the cashier stays signed in and the supervisor walks away
// (architecture §11.3).
//
// `tests/test_edge_function_parity.py` asserts that no function but
// `authenticate-pin` mints a session, so the deletion cannot be undone by
// accident later.
//
// Deploy:  supabase functions deploy authorize-override --no-verify-jwt
// (--no-verify-jwt for the same reason as its neighbour: the till's own
// session belongs to the cashier, not to the approver being checked.)

import { createClient } from "jsr:@supabase/supabase-js@2";
import { argon2Verify } from "npm:hash-wasm@4";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

// No ANON_KEY here, deliberately. Its only use next door is minting a session
// through the public client, and this function does not mint sessions. An
// unused import of a key is the kind of thing that gets used.

// ── argon2id ────────────────────────────────────────────────────────────────
//
// Verification only. An argon2 hash carries its own parameters, so nothing
// here needs to know the cost — which is why the minting constants next door
// are absent rather than copied.
//
// Re-minting an old-cost hash is also absent, and that is a decision:
// `authenticate-pin` does it because it is the login path and holds the
// plaintext PIN at the one moment a rehash is possible. Doing it here as well
// would mean two functions writing to `employees.pin_hash`, for a saving that
// the next sign-in collects anyway.
//
// The decoy stays, because the timing attack it defeats is the same one. It
// must carry the same parameters as a real hash or it is not a decoy — an
// unknown code that answers faster than a wrong PIN is an employee roster
// with a stopwatch. Generated by `scripts/remint_pin_hashes.py`, not typed.
const DECOY_HASH = "$argon2id$v=19$m=65536,t=3,p=4$5EGpi0dpbH7a2BemXBBVwg$MuglEN3+wAVgYzNtkw7mzMl9SScqMEG7OoEXAkhDF3U";

// Same shape as the limiter in `authenticate-pin`, and the same caveat, which
// matters more here than it does there.
//
// Per instance, and only per instance. `attempts` lives in the memory of one
// Deno isolate; the platform cold-starts, recycles and scales these
// horizontally, so this is a nominal figure rather than a property of the
// system. It raises the cost of casual guessing and nothing more.
//
// The binding throttle for this path is on the terminal:
// `app/domain/lockout.py` counts consecutive failures in SQLite, escalates,
// and survives a restart — and `AuthService` consults it *before* it chooses
// between this function and the local cache, so being online changes who
// verifies the PIN and not whether this approver may be asked at all. Do not
// read the numbers below as the protection. They are the floor.
const MAX_ATTEMPTS = 10;
const WINDOW_MS = 5 * 60 * 1000;
const attempts = new Map<string, { count: number; resetAt: number }>();

function rateLimited(key: string): boolean {
  const now = Date.now();
  const entry = attempts.get(key);
  if (!entry || now > entry.resetAt) {
    attempts.set(key, { count: 1, resetAt: now + WINDOW_MS });
    return false;
  }
  entry.count += 1;
  return entry.count > MAX_ATTEMPTS;
}

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });

// One shape for a rejected credential, as next door: telling "no such
// employee" apart from "wrong PIN" turns the endpoint into a staff roster.
const reject = () => json({ error: "invalid_credentials" }, 401);

interface OverrideBody {
  approver_code?: string;
  pin?: string;
  store_code?: string;
  permission?: string;
}

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  let body: OverrideBody;
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid_json" }, 400);
  }

  const approverCode = (body.approver_code ?? "").trim().toUpperCase();
  const pin = body.pin ?? "";
  const storeCode = (body.store_code ?? "").trim().toUpperCase();
  const permission = (body.permission ?? "").trim();

  if (!approverCode || !pin || !storeCode || !permission) {
    return json({ error: "missing_fields" }, 400);
  }
  if (rateLimited(`${approverCode}:${storeCode}`)) {
    return json({ error: "too_many_attempts" }, 429);
  }

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data: store } = await admin
    .from("stores")
    .select("id")
    .eq("code", storeCode)
    .eq("is_active", true)
    .maybeSingle();
  if (!store) return reject();

  const { data: approver } = await admin
    .from("employees")
    .select("user_id, employee_code, full_name, pin_hash, status")
    .eq("employee_code", approverCode)
    .maybeSingle();

  const hash = approver?.pin_hash ?? DECOY_HASH;

  let pinOk = false;
  try {
    pinOk = await argon2Verify({ password: pin, hash });
  } catch {
    pinOk = false;
  }
  if (!approver || !pinOk) return reject();

  if (approver.status !== "active") {
    return json({ error: "account_disabled" }, 403);
  }

  // Roles are per store, so an area manager with no role in *this* store
  // cannot authorise here — the same rule that decides whether they could
  // sign in.
  const { data: roleRows } = await admin
    .from("user_store_roles")
    .select("role_key")
    .eq("user_id", approver.user_id)
    .eq("store_id", store.id);

  const roles = (roleRows ?? []).map((r: { role_key: string }) => r.role_key);
  if (roles.length === 0) return reject();

  // **Read the permission; never take the caller's word for it.**
  //
  // The body names a permission because the terminal has to say what is being
  // asked for. Whether this person holds it is decided here, from
  // `role_permissions`, exactly as the offline path decides it from the
  // cached snapshot. Skipping this — trusting a `permission` the client sent,
  // or returning the approver's whole permission list for the terminal to
  // check — would make the online path looser than the offline one, which is
  // the inversion the terminal's throttle exists to prevent elsewhere. Nobody
  // can lend what they do not hold, on either side of the wire.
  const { data: permissionRows } = await admin
    .from("role_permissions")
    .select("permission_key")
    .in("role_key", roles)
    .eq("permission_key", permission);

  if (!permissionRows || permissionRows.length === 0) {
    // Only reachable after a correct PIN, so it discloses nothing an attacker
    // could use: you have to already be the approver to learn that the
    // approver lacks a key. The terminal needs it as a distinct answer
    // because the screen says something different — fetch somebody more
    // senior, rather than retype.
    return json({ error: "approver_lacks_permission" }, 403);
  }

  // Whether this permission is lendable *at all* is not decided here. That is
  // `app/domain/permissions.py`'s `OVERRIDABLE`, checked on the terminal
  // before anybody is asked for a PIN and enforced again by
  // `SessionStore.grant`, which is where the grant is actually minted. A copy
  // of that list in this file would be a fourth duplicated constant with
  // nothing to hold it in step, protecting a decision that is already made
  // twice on the only machine that can act on it.
  //
  // No `pin_hash` in the response either. Returning it would cache the
  // approver on this till as a side effect of one authorisation, which is a
  // different act from signing in and should stay one: an online override
  // works for somebody who has never touched this terminal, and an offline
  // one still does not.
  //
  // No grant window either — `OVERRIDE_GRANT_TTL` belongs to the terminal
  // that mints the grant, and a second authority on the same number is how
  // two clocks start disagreeing.
  return json({
    approver: {
      user_id: approver.user_id,
      employee_code: approver.employee_code,
      full_name: approver.full_name,
      store_id: store.id,
      roles,
    },
    permission,
    verified_at: new Date().toISOString(),
  });
});
